[build]
  command = "npm run build-archive"
  functions = "dist/functions"

[build.environment]
  GIT_LFS_ENABLED = true

[template.environment]
  BOT_TOKEN = "discord bot token here"
  CHANNEL_ID = "discord channel id for invite"
  GUILD_ID = "discord guild id"
  CLIENT_ID = ""
  CLIENT_SECRET = ""
  OAUTH_SCOPES = "identify email"
  REDIRECT_URI = "https://example.com/api/callback"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 301

[[redirects]]
  from = "/discord"
  to = "/api/invite"
  status = 301